Repository noyamirai/cmd-online, pull requests merged in 2022-04, with the labels that each got.

#47 ⚡ feat(cms & dashboard): adding course CRUD operations and fixed student dashboard
  models/schemas.js
  public/js/cms-script.js
  public/styles/form.css
  public/styles/style.css
  public/uploads/profile_pic-1648820175853.png
  public/uploads/profile_pic-1648841693103.jpeg
  public/uploads/profile_pic-1648842139218.jpeg
  routes/dashboard.js
  routes/maintenance.js
  routes/overviews.js
  routes/users.js
  views/class-details.ejs
  views/cms/form.ejs
  views/cms/partials/course-form.ejs
  views/courses-overview.ejs
  views/index.ejs
  views/partials/profile-banner.ejs
Labels: enhancement, feature, HTML/CSS

#49 ⚡ feat(dashboard): dashboard for all user types functional after profile setups
  controller/crud-operations.js
  models/schemas.js
  routes/overviews.js
  routes/profile.js
  routes/settings.js
  views/class-details.ejs
  views/courses-overview.ejs
  views/profile.ejs
Labels: refactor, feature, HTML/CSS

#51 feature: users can now logout
  public/styles/button.css
  public/uploads/profile_pic-1648904920029.jpeg
  routes/dashboard.js
  routes/users.js
  views/index.ejs
Labels: enhancement

#53 ⚡ feat(team generator): fully functional team generator
  controller/crud-operations.js
  controller/team-generator.js
  models/schemas.js
  public/js/form-script.js
  public/styles/form.css
  public/styles/style.css
  public/uploads/profile_pic-1648915402941.png
  public/uploads/profile_pic-1648915735653.png
  public/uploads/profile_pic-1648915922131.png
  public/uploads/profile_pic-1648916006968.png
  public/uploads/profile_pic-1648916082058.png
  public/uploads/profile_pic-1648916149478.png
  public/uploads/profile_pic-1648916219516.png
  public/uploads/profile_pic-1648916278233.png
  routes/dashboard.js
  routes/overviews.js
  routes/users.js
  views/class-details.ejs
  views/class-home.ejs
  views/index.ejs
  views/partials/form.ejs
  views/partials/head.ejs
  views/team-details.ejs
  views/team-generation.ejs
  views/team-overview.ejs
Labels: feature, priority, HTML/CSS

#54 Feature: Node-mailer
  README.md
  package-lock.json
  package.json
  public/styles/header.css
  public/styles/style.css
  routes/dashboard.js
  routes/users.js
  server.js
  views/index.ejs
Labels: feature

#55 ⚡ feat(cms): working CRUD operations for courses and classes
  controller/crud-operations.js
  gulpfile.js
  package-lock.json
  package.json
  public/styles/form.css
  routes/maintenance.js
  views/cms/confirmation.ejs
  views/cms/form.ejs
  views/cms/index.ejs
  views/cms/overview.ejs
  views/cms/partials/class-form.ejs
  views/cms/partials/overview-form.ejs
Labels: feature

#57 🚫 Bug: error on sign up when not submitting an image
  package-lock.json
  package.json
  public/uploads/profile_pic-1648729729901.gif
  public/uploads/profile_pic-1648731905927.gif
  routes/users.js
Labels: bug

#58 ⚡ feat(errors): added error styling
  public/styles/error.css
  routes/users.js
  views/login.ejs
  views/partials/messages.ejs
Labels: enhancement, HTML/CSS

#60 Feature: error handling for login page is complete
  config/verifyUser.js
  routes/users.js
  server.js
  views/login.ejs
  views/partials/messages.ejs
Labels: bug, feature, priority

#59 ⚙️ refactor(all): added comments where needed
  controller/crud-operations.js
  controller/team-generator.js
  models/schemas.js
  public/js/form-script.js
  routes/dashboard.js
  routes/maintenance.js
  routes/overviews.js
  routes/settings.js
  routes/skills.js
  routes/users.js
  views/courses-overview.ejs
  views/index.ejs
  views/login.ejs
  views/register.ejs
Labels: refactor
