Repository noyamirai/cmd-online, pull requests merged in 2022-03, with the labels that each got.

#2 ⚡ feat(team generator): added all necessary overview pages
  controller/team-generator.js
  server.js
  views/class-details.ejs
  views/class-home.ejs
  views/classes-overview.ejs
  views/courses-overview.ejs
  views/partials/footer.ejs
  views/partials/form.ejs
  views/partials/profile-banner.ejs
  views/partials/title-banner.ejs
Labels: help wanted, question

#12 ⚡ feat(overview): created routes and cleaned code
  routes/overviews.js
  server.js
  views/class-details.ejs
  views/class-home.ejs
  views/classes-overview.ejs
  views/courses-overview.ejs
  views/partials/profile-banner.ejs
Labels: feature, needs feedback

#17 Feature: user login complete
  config/verifyUser.js
  routes/users.js
  server.js
  views/login.ejs
Labels: feature

#24 refactor(index): changed title
  views/index.ejs
Labels: refactor, needs feedback

#29 🎨 refactor(css): added css modules and minify process with gulp
  gulpfile.js
  package-lock.json
  package.json
  public/styles/button.css
  public/styles/footer.css
  public/styles/form.css
  public/styles/header.css
  public/styles/style.css
  public/styles/utils.css
  views/partials/head.ejs
Labels: enhancement, refactor, HTML/CSS

#38 ⚡ feat(profile): did stuff
  package-lock.json
  package.json
  routes/profile.js
  server.js
  views/profile.ejs
Labels: feature, needs feedback, HTML/CSS

#40 ⚡ feat(profile setup): HTML/CSS and working CRUD operations
  README.md
  config/base-db.js
  controller/crud-operations.js
  models/schemas.js
  public/images/icons/settings-icon.svg
  public/styles/button.css
  public/styles/form.css
  public/styles/header.css
  public/styles/style.css
  routes/dashboard.js
  routes/maintenance.js
  routes/profile.js
  routes/settings.js
  server.js
  views/cms/form.ejs
  views/cms/index.ejs
  views/cms/partials/course-form.ejs
  views/index.ejs
  views/partials/select-input.ejs
  views/profile.ejs
Labels: refactor, feature, HTML/CSS

#42 ⚡ feat(skills): HTML/CSS added and working CRUD
  models/schemas.js
  public/styles/header.css
  public/styles/style.css
  routes/dashboard.js
  routes/settings.js
  routes/skills.js
  server.js
  views/index.ejs
  views/skills.ejs
Labels: feature, HTML/CSS

#46 users can now upload a profile picture and see it on their profile
  models/schemas.js
  package-lock.json
  package.json
  public/uploads/profile_pic-1648727312779.gif
  routes/users.js
  server.js
  views/index.ejs
  views/register.ejs
Labels: enhancement, feature, HTML/CSS
